[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Blueprint Compat Jokers Part 1
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "elseif self.ability.name == 'Blueprint' then"
position = "before"
payload = '''
elseif self.config.center.key == 'j_unstb_plagiarism' then
    self.ability.blueprint_compat_ui = self.ability.blueprint_compat_ui or ''; self.ability.blueprint_compat_check = nil
    main_end = (self.area and self.area == G.jokers) and {
        {n=G.UIT.C, config={align = "bm", minh = 0.4}, nodes={
            {n=G.UIT.C, config={ref_table = self, align = "m", colour = G.C.JOKER_GREY, r = 0.05, padding = 0.06, func = 'blueprint_compat'}, nodes={
                {n=G.UIT.T, config={ref_table = self.ability, ref_value = 'blueprint_compat_ui',colour = G.C.UI.TEXT_LIGHT, scale = 0.32*0.8}},
            }}
        }}
    } or nil
'''
match_indent = true 

# Blueprint Compat Jokers Part 2
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Blueprint' or self.ability.name == 'Brainstorm' then"
position = "before"
payload = '''
if self.config.center.key == 'j_unstb_plagiarism' then
	local other_joker = nil
    for i = 1, #G.jokers.cards do
            if G.jokers.cards[i] == self then
				if self.ability.extra.dir == 0 then
					other_joker = G.jokers.cards[i-1]
				else
					other_joker = G.jokers.cards[i+1]
				end
			end
        end
	
    if other_joker and other_joker ~= self and other_joker.config.center.blueprint_compat then
        self.ability.blueprint_compat = 'compatible'
    else
        self.ability.blueprint_compat = 'incompatible'
    end
end
'''
match_indent = true

# Adds support for Virtual Money (used for IC Card)
[[patches]]
[patches.regex]
target = 'functions/button_callbacks.lua'
pattern = '''G.GAME.dollars[ ]*-[ ]*G.GAME.bankrupt_at'''
position = 'at'
payload = '''G.GAME.dollars + (G.GAME.virtual_dollars or 0) - G.GAME.bankrupt_at'''